### ISSUE TITLE
GG 4.1

### ISSUE THREAD

**Issue by altexy** [GluuFederation/docker-gg#10]
We did release GG 4.1.0 some weeks ago.
This release is fixed with `v4.1.0` tag https://github.com/GluuFederation/gluu-gateway/tree/v4.1.0

Please, add appropriate branch, change the Dockerfile to get the tag above, build the image and push to Dockerhub.

Keep in mind that branches `version_4.1` and `version_4.2` should still produce rolling `dev` versions, preferably also rebuilt on Dockerhub on every change.

It will help out potential customers to test GG.

**Comment by mirr254** [comment]
Noted. I will work on it

**Comment by mirr254** [comment]
@altexy The issue has been resolved. And both 4.1 and 4.2 have `_dev` verisons
