### ISSUE TITLE
4.1 recent Dockerfile changes

### ISSUE THREAD

**Issue by altexy** [GluuFederation/docker-gg#7]
Hi, we will update all GG submodules to `https` scheme in version_4.1 branch soon.

Now the single command `git clone --recursive --depth 1 --branch version_4.1 https://github.com/GluuFederation/gluu-gateway.git` should work in Dockerfile, no needs of your own `gitmodules` copy and submodule update.
.
Also IMO you don't need `install-plugins.sh` script - it may be done within Dockerfile,
please, take a look at https://github.com/GluuFederation/gluu-gateway/blob/kong_2.0/Dockerfile

Also, there is some user permission stuff, take a look at USER directives.

**Comment by altexy** [comment]
And we bump Kong version to 2.0.0

**Comment by altexy** [comment]
I will post here when branch `version_4.1` will be ready - we need some time to test.
Posted in advance to not forget ;-)

**Comment by altexy** [comment]
Changes have been merged into GG `version_4.1` branch.
Please, process with it.

**Comment by mirr254** [comment]
I will go ahead and work on this. Apologies if I saw the update or the go-ahead late.

**Comment by mirr254** [comment]
On the issue of not using the script `install-plugins.sh`,  the reason for using it is to reduce the number of layers being created while our image is being built. This in-turn reduces significantly the size of the image we push to docker hub.

If you look at these lines https://github.com/GluuFederation/gluu-gateway/blob/version_4.1/Dockerfile#L26-L32 they are alot of them, and each one creates a layer on build thus increasing the image size as compared to having one layer that runs the script.

While testing this might not be a very big issue, but I believe in prod users might want to work with small-sized images.

What do you think?

**Comment by altexy** [comment]
@mirr254 IMO it would be a good idea do not produce redundant artifacts.

First, we don't plan to support `https://github.com/GluuFederation/gluu-gateway/raw/${GLUU_VERSION}/${GG_DEPS}.zip` files anymore.

Nowadays one of the Docker best practices is to use multi-stage builds.

It should be possible to build all required Lua folder structures in the intermediate stage and copy all by one COPY directive in the final image.
**One another layer** will replace/remove exiting Kong files (the example is in our test Dockerfile)

All ENV may be set in one layer.

IMO re resulting image would have less layers the 4.0 version.
My 2 cents

**Comment by iromli** [comment]
@altexy 

> First, we don't plan to support https://github.com/GluuFederation/gluu-gateway/raw/${GLUU_VERSION}/${GG_DEPS}.zip files anymore.

Agreed.

But we need to fetch submodules. I've tried the Dockerfile which resulting:

```
» make
[I] Building Docker image gluufederation/gluu-gateway:4.1.0_dev
Sending build context to Docker daemon  20.48kB
Step 1/21 : FROM kong:2.0.0-alpine
2.0.0-alpine: Pulling from library/kong
4167d3e14976: Downloading [====>                                           4167d3e14976: Pull complete 
e3498c42495a: Pull complete 
a6fb7cf8d4a3: Pull complete 
Digest: sha256:be25939f25124e020ea1d1726c670bdf8920a3044e195a46b33eb80d20a24d64
Status: Downloaded newer image for kong:2.0.0-alpine
 ---> 13f14d790da4
Step 2/21 : ARG LUA_DIST=/usr/local/share/lua/5.1
 ---> Running in 1b79aa9edf63
Removing intermediate container 1b79aa9edf63
 ---> 7689e24e4862
Step 3/21 : ARG DISABLED_PLUGINS="ldap-auth key-auth basic-auth hmac-auth jwt oauth2"
 ---> Running in 071f910e68ac
Removing intermediate container 071f910e68ac
 ---> 6f00d8194b0a
Step 4/21 : USER root
 ---> Running in d1f81f486dc2
Removing intermediate container d1f81f486dc2
 ---> 4bfe398b7a45
Step 5/21 : COPY lib/ ${LUA_DIST}/
COPY failed: stat /var/lib/docker/tmp/docker-builder246005598/lib: no such file or directory
Makefile:6: recipe for target 'build-dev' failed
make: *** [build-dev] Error 1
```

@mirr254 please adjust current Dockerfile in this repo to conform to latest Gluu Gateway.

**Comment by iromli** [comment]
@mirr254 

> If you look at these lines https://github.com/GluuFederation/gluu-gateway/blob/version_4.1/Dockerfile#L26-L32 they are alot of them, and each one creates a layer on build thus increasing the image size as compared to having one layer that runs the script.

We might be able to overcome your concern by modifying the multiples `COPY` directives with single `RUN cp`.

**Comment by mirr254** [comment]
@altexy @iromli PR is up and ready to review #8

**Comment by iromli** [comment]
Changes have been applied.
